### ISSUE TITLE
[Enhancement] Add video skip function

### ISSUE THREAD

**Issue by AltronMaxX** [MasterEric/extension-ffmpeg#33]
I think you don't need explanation why it will be useful.

**Comment by EliteMasterEric** [comment]
Are you referring to a seek function (which would let you move the video to a specific position)? 

If so, that would be covered by #26.

If not, and you're just referring to "Add a key to stop a video," that's very easy to implement in the application using this library (and may not make sense for some uses of video) so I don't see any reason to implement it.

**Comment by AltronMaxX** [comment]
I meant first option :)

**Comment by EliteMasterEric** [comment]
Ok that is covered by #26 in the Discussions page.
